package de.tototec.tools.cmvn;

// Class generated by cmvn
public abstract class Config {

	public static String cmvnVersion() {
		return "0.1.9-SNAPSHOT";
	}

	public static String cmvnOsgiVersion() {
		return "0.1.8.9000";
	}

	public static String cmvnCompatibleOsgiVersion() {
		return "0.1.0";
	}

}
