package de.tototec.cmvn;

// Class generated by cmvn
public abstract class Config {

	public static String cmvnVersion() {
		return "0.2.0";
	}

	public static String cmvnOsgiVersion() {
		return "0.2.0";
	}

	public static String cmvnCompatibleOsgiVersion() {
		return "0.1.0";
	}

}
